"""Initial migration

Revision ID: a28e9c10a85e
Revises: 051e88220f46
Create Date: 2026-07-28 07:07:37.320886+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.dialects import postgresql
from alembic import context
from alembic import op

from migration import routines
from migration import data

# revision identifiers, used by Alembic.
revision: str = "a28e9c10a85e"
down_revision: str | None = "051e88220f46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()

    return


def downgrade() -> None:
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_downgrades()
    schema_downgrades()

    return


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fot_role",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "source",
            sa.String(length=16),
            server_default=sa.text("'INTERNAL'"),
            nullable=False,
        ),
        sa.Column(
            "protected", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "description",
            sa.String(length=256),
            server_default=sa.text("''"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__fot_role")),
        sa.UniqueConstraint("name", name=op.f("uq__fot_role__name")),
    )
    op.create_index(
        op.f("ix__fot_role__created_at"), "fot_role", ["created_at"], unique=False
    )
    op.create_table(
        "fot_scope",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=128), nullable=False),
        sa.Column(
            "protected", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "description",
            sa.String(length=256),
            server_default=sa.text("''"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__fot_scope")),
        sa.UniqueConstraint("value", name=op.f("uq__fot_scope__value")),
    )
    op.create_index(
        op.f("ix__fot_scope__created_at"), "fot_scope", ["created_at"], unique=False
    )
    op.create_table(
        "fot_table_stat",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("table_name", sa.String(length=64), nullable=False),
        sa.Column(
            "insert_count", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "delete_count", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "row_count", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "0 <= delete_count",
            name=op.f("ck__fot_table_stat__delete_count__non_negative"),
        ),
        sa.CheckConstraint(
            "0 <= insert_count",
            name=op.f("ck__fot_table_stat__insert_count__non_negative"),
        ),
        sa.CheckConstraint(
            "0 <= row_count", name=op.f("ck__fot_table_stat__row_count__non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__fot_table_stat")),
        sa.UniqueConstraint("table_name", name=op.f("uq__fot_table_stat__table_name")),
    )
    op.create_index(
        op.f("ix__fot_table_stat__created_at"),
        "fot_table_stat",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "fot_user",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column(
            "timezone",
            sa.String(length=32),
            server_default=sa.text("'UTC'"),
            nullable=False,
        ),
        sa.Column(
            "protected", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("last_login_ip", postgresql.INET(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__fot_user")),
        sa.UniqueConstraint("email", name=op.f("uq__fot_user__email")),
    )
    op.create_index(
        op.f("ix__fot_user__created_at"), "fot_user", ["created_at"], unique=False
    )
    op.create_table(
        "fot_role_scope",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("role_name", sa.String(length=64), nullable=False),
        sa.Column("scope_value", sa.String(length=128), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_name"],
            ["fot_role.name"],
            name=op.f("fk__fot_role_scope__role_name"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scope_value"],
            ["fot_scope.value"],
            name=op.f("fk__fot_role_scope__scope_value"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__fot_role_scope")),
        sa.UniqueConstraint(
            "role_name",
            "scope_value",
            name="uq__fot_role_scope__role_name__scope_value",
        ),
    )
    op.create_index(
        op.f("ix__fot_role_scope__created_at"),
        "fot_role_scope",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "fot_user_api_key",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
        sa.Column(
            "allowed_scopes",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "allowed_ips",
            postgresql.ARRAY(postgresql.INET()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_ip", postgresql.INET(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["fot_user.id"],
            name=op.f("fk__fot_user_api_key__user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__fot_user_api_key")),
        sa.UniqueConstraint(
            "key_prefix", "key_hash", name="uq__fot_user_api_key__key_prefix__key_hash"
        ),
    )
    op.create_index(
        op.f("ix__fot_user_api_key__created_at"),
        "fot_user_api_key",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix__fot_user_api_key__key_hash"),
        "fot_user_api_key",
        ["key_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix__fot_user_api_key__key_prefix"),
        "fot_user_api_key",
        ["key_prefix"],
        unique=False,
    )
    op.create_table(
        "fot_user_role",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("role_name", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_name"],
            ["fot_role.name"],
            name=op.f("fk__fot_user_role__role_name"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["fot_user.id"],
            name=op.f("fk__fot_user_role__user_id"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__fot_user_role")),
        sa.UniqueConstraint(
            "user_id", "role_name", name="uq__fot_user_role__user_id__role_name"
        ),
    )
    op.create_index(
        op.f("ix__fot_user_role__created_at"),
        "fot_user_role",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "fot_user_token",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_ip", postgresql.INET(), nullable=True),
        sa.Column("family_token_id", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["fot_user.id"],
            name=op.f("fk__fot_user_token__user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__fot_user_token")),
        sa.UniqueConstraint(
            "user_id",
            "kind",
            "token_hash",
            name="uq__fot_user_token__user_id__kind__token_hash",
        ),
    )
    op.create_index(
        op.f("ix__fot_user_token__created_at"),
        "fot_user_token",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix__fot_user_token__family_token_id"),
        "fot_user_token",
        ["family_token_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__fot_user_token__token_hash"),
        "fot_user_token",
        ["token_hash"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Functions and triggers
    routines.create_all_tables_fn_tr()
    return


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__fot_user_token__token_hash"), table_name="fot_user_token")
    op.drop_index(
        op.f("ix__fot_user_token__family_token_id"), table_name="fot_user_token"
    )
    op.drop_index(op.f("ix__fot_user_token__created_at"), table_name="fot_user_token")
    op.drop_table("fot_user_token")
    op.drop_index(op.f("ix__fot_user_role__created_at"), table_name="fot_user_role")
    op.drop_table("fot_user_role")
    op.drop_index(
        op.f("ix__fot_user_api_key__key_prefix"), table_name="fot_user_api_key"
    )
    op.drop_index(op.f("ix__fot_user_api_key__key_hash"), table_name="fot_user_api_key")
    op.drop_index(
        op.f("ix__fot_user_api_key__created_at"), table_name="fot_user_api_key"
    )
    op.drop_table("fot_user_api_key")
    op.drop_index(op.f("ix__fot_role_scope__created_at"), table_name="fot_role_scope")
    op.drop_table("fot_role_scope")
    op.drop_index(op.f("ix__fot_user__created_at"), table_name="fot_user")
    op.drop_table("fot_user")
    op.drop_index(op.f("ix__fot_table_stat__created_at"), table_name="fot_table_stat")
    op.drop_table("fot_table_stat")
    op.drop_index(op.f("ix__fot_scope__created_at"), table_name="fot_scope")
    op.drop_table("fot_scope")
    op.drop_index(op.f("ix__fot_role__created_at"), table_name="fot_role")
    op.drop_table("fot_role")
    # ### end Alembic commands ###

    # Drop functions
    routines.drop_all_tables_fn()
    return


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

    _bind = op.get_bind()
    with Session(bind=_bind) as _session:
        data.populate_all(session=_session)

    return


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""

    data.drop_all()
    return
